default: &default

  address: "smtp.mailgun.org"
  port: "587"
  domain: "raisingstars.co.mailgun.org"
  authentication: "plain"
  user_name: "postmaster@raisingstars.co.mailgun.org"
  password: "wlagqdlkaumzlplp"
  enable_starttls_auto: true

development:
  <<: *default
