default: &default
  address: "smtp.gmail.com"
  port: "587"
  domain: "gmail.com"
  authentication: "plain"
  user_name: "howclf@gmail.com"
  password: "wlagqdlkaumzlplp"
  enable_starttls_auto: true

development:
  <<: *default
